# Generated by Django 3.2.8 on 2021-11-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pubDate', models.DateTimeField()),
                ('text', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=30)),
            ],
        ),
    ]
